export const projects = [
  {
    id: 1,
    name: "Masa Yang Akan Datang",
    tools: ["Unity", "C#"],
    sourceCode: "https://github.com/mattsmatt/MasaYangAkanDatang",
    website: "",
    app: "https://mattsmatt.itch.io/masa-yang-akan-datang",
    description: [
      "This game was built for my thesis in a group of three to observe how an adventure-RPG (Role Playing Game) game can increase AI awareness and acceptance within the general public",
      "It was built using Unity as the main game engine and C# as the back-end programming language. The game was designed for mobile phones running on Android",
      "It contains numerous game mechanics, including but not limited to turned-based RPG alongside puzzle minigames",
      "The related thesis showcased that after playing the game, users showed an improvement both for AI awareness and acceptance by 4.37% and 4.84% respectively",
    ],
    image: "masa-yang-akan-datang.png",
  },
  {
    id: 2,
    name: "Traffic Estimator",
    tools: ["Python", "YOLOv7", "Computer Vision"],
    sourceCode: "https://github.com/mattsmatt/traffic-estimator-system",
    website: "",
    app: "",
    description: [
      "This traffic monitoring system utilized the YOLOv7 model in conjunction with a SORT filter to track vehicle count and average speed using a custom dataset comprising car images and CCTV footage of Malang's traffic",
      "According to the findings, the YOLOv7 system exhibited higher average precision, achieving 61.3%, 78.6%, and 62.1% for each test, and boasted a faster average inference time of 90.67 seconds, meeting the requirements of an intelligent transportation system",
      "The system was built in a group of three for my Research Methodology in Computer Science paper, which was eventually published in November 2024 as a part of Procedia Computer Science Volume 245",
    ],
    image: "traffic-estimator-system.png",
  },
  {
    id: 3,
    name: "KPopZtation",
    tools: ["ASP .NET", "C#", "Microsoft SQL"],
    sourceCode: "https://github.com/mattsmatt/Kpopztation",
    website: "",
    app: "",
    description: [
      "A K-Pop album store website where guests can view albums, registered users / customers can order albums, and administrators can manage the catalog",
      "The project was built in a group of four using ASP .NET, Microsoft SQL, alongside C# as well as Domain Driven Design (DDD) for the software design approach",
    ],
    image: "kpopztation.png",
  },
  {
    id: 4,
    name: "GoVege",
    tools: ["ASP .NET", "C#", "Microsoft SQL"],
    sourceCode: "https://github.com/mattsmatt/GoVege",
    website: "",
    app: "",
    description: [
      "A service for customers to order vegan and vegetarian food, view promos, and manage their account",
      "On the other hand, administrators can manage the listed restaurants, promos, and other data",
      "The web application was built in a team of 4 for my Software Engineering course's final project usign ASP .NET for front-end development, C# for backend, and Microsoft SQL as the database",
    ],
    image: "govege.png",
  },
  {
    id: 5,
    name: "Internet-CLafes",
    tools: ["Java", "MySQL", "JavaFX"],
    sourceCode: "https://github.com/mattsmatt/Internet-CLafes",
    website: "",
    app: "",
    description: [
      "A desktop application that provides an online platform for customers to book PCs for an internet cafe in advance so they can use them during d-day",
      "The user roles consist of administrators, computer technicians, operators, and customers",
      "Customers can book PCs, operators can process those orders, computer technicians can process broken computer cases, while administrators can manage technician job, PC, and report data",
      "The application was built with Java and MySQL for database purposes, alongside JavaFX for the front-end",
    ],
    image: "internet-clafes.png",
  },
  {
    id: 6,
    name: "Tanaka Guitar",
    tools: ["HTML", "CSS", "JavaScript"],
    sourceCode: "https://github.com/mattsmatt/Tanaka-Guitar",
    website: "",
    app: "",
    description: [
      "This project was done for my Human Computer Interaction class' final project in a group of two",
      "The project was aimed to provide a front-end interface for a guitar shop's website",
      "It was built with HTML5, CSS, and JavaScript on the programming side, alongside Figma for UI/UX design purposes",
    ],
    image: "tanaka-guitar.png",
  },
];
